"""update

Revision ID: 62e861c96e2e
Revises: 37432833a177
Create Date: 2022-06-29 09:31:57.787650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62e861c96e2e'
down_revision = '37432833a177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reply_thread', sa.Column('reply_id', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'reply_thread', type_='foreignkey')
    op.create_foreign_key(None, 'reply_thread', 'reply', ['reply_id'], ['id'])
    op.create_foreign_key(None, 'reply_thread', 'reply_thread', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reply_thread', type_='foreignkey')
    op.drop_constraint(None, 'reply_thread', type_='foreignkey')
    op.create_foreign_key(None, 'reply_thread', 'reply', ['parent_id'], ['id'])
    op.drop_column('reply_thread', 'reply_id')
    # ### end Alembic commands ###
