"""update

Revision ID: 749be7203141
Revises: 62e861c96e2e
Create Date: 2022-06-29 13:44:10.453350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749be7203141'
down_revision = '62e861c96e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reply_thread', sa.Column('depth', sa.Integer(), nullable=True))
    op.drop_constraint(None, 'reply_thread', type_='foreignkey')
    op.create_foreign_key(None, 'reply_thread', 'reply_thread', ['parent_id'], ['id'])
    op.create_foreign_key(None, 'reply_thread', 'reply', ['reply_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reply_thread', type_='foreignkey')
    op.drop_constraint(None, 'reply_thread', type_='foreignkey')
    op.create_foreign_key(None, 'reply_thread', 'reply', ['parent_id'], ['id'])
    op.drop_column('reply_thread', 'depth')
    # ### end Alembic commands ###
