"""empty message

Revision ID: 95c77bc6f6f6
Revises: 08f1737eec98
Create Date: 2022-06-28 09:11:12.487485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95c77bc6f6f6'
down_revision = '08f1737eec98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post', 'user', ['poster_id'], ['id'])
    op.drop_column('post', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author', sa.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    # ### end Alembic commands ###
